### PR TITLE
Coordinator CI

### PR DESCRIPTION
**Pull request by danielabrozzoni**

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
I hereby invoke @darosior, as the CI is not running and I'm not really sure where to look. Perhaps the workflow should be in master to work? I have no idea

**Comment by darosior** [comment]
Think we need to merge it for it to be triggered

**Comment by danielabrozzoni** [comment]
Ouch :( Then I'll test it locally with the GA image, wish me luck...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by darosior** [comment]
uACK ceb61fe -- the config looks good to me from a quick skim

**Pull request merged**
