### PR TITLE
Fuzzing in CI

### PR DESCRIPTION
**Pull request by danielabrozzoni**

### CODE REVIEW

**Comment by darosior** [comment]
You are missing the database therefore it fails

**Comment by danielabrozzoni** [comment]
Ops! Should be ok now

**Comment by darosior** [comment]
utACK 17b5511e4602142d58828c70b706162be2b368ae

**Comment by danielabrozzoni** [comment]
Pushed again, same code, but the commit is signed

**Comment by darosior** [comment]
And now it's failing xD

**Comment by danielabrozzoni** [comment]
Nightly was the culprit, I feel like a detective now 🕵🏻‍♀️ 

ACK dd834962de4c4c77463b4e94486a70554d31b678

**Pull request merged**
